prompt("masukan nama kamu :");
alert("HI Selvi");
alert("senang berkenalan dengan kamu");
alert("walaupun hari ini hujan");
alert("semoga kehadiran kamu tetap mewarnai hati aku ya :) ");
alert("semangat menjalani aktivitasnya");
alert("kamu cantik, manis, lucu gabikin bosen");
alert("tapi sayang :( ");
alert("pasti kamu nanya tapi sayang kenapa kan??");
alert("iyaa, sayang betul lama lama bisa sayang");
alert("aku paham ko ga gampang untuk dapet perhatian kamu");
alert("aku juga tau diri ko");
alert("aku cuma berusaha saja untuk dapet first attantion kamu :)");
alert("mau gimana pun kedepannya yang penting aku sudah berusaha");
alert("selamat malam cantik, one and only people yang first conversation udah bisa bikin aku mimpi tentang kamu");
alert("cape yah ngekliknya?");
alert("maaf ya cantik, aku terlalu sering menghubungimu");
alert("tapi, kalo kamu gamau dihubungi atau kamu lebih prioritasin yang lain gpp ko :) ");
alert("aku cuma senang saja ketemu kamu, ya walaupun masih gagu untuk bicaranya");
alert("wah, udah kepanjangan nih udahan ya?");
alert("tapi, masih banyak sih yang mau aku sampein");
alert("jujur aku baper");
alert("udah ah sampe situ aja wkwkw");
alert("jangan ditutup dulu pleasee");
alert("hehe cape ya ngekliknya?, ya itung itung gantinya bete aku tadi, karena udah semangat ketemu kamu tapi gajadi");
alert("tapi yaudahlah ya ");
alert("satu klik lagi udahan");
alert("ett, tapi bong hiya hiya hiya");
alert("kali ini beneran udahan ko");
alert("ett tapi boong lgi wwkwkwk");
alert("selamat malam dan selamat pagi manis");
